var annotated_dup =
[
    [ "math", "namespacemath.html", [
      [ "Vector3D", "structmath_1_1_vector3_d.html", "structmath_1_1_vector3_d" ]
    ] ],
    [ "scene", "namespacescene.html", [
      [ "GameClearScene", "classscene_1_1_game_clear_scene.html", "classscene_1_1_game_clear_scene" ],
      [ "GameOverScene", "classscene_1_1_game_over_scene.html", "classscene_1_1_game_over_scene" ],
      [ "PlayScene", "classscene_1_1_play_scene.html", "classscene_1_1_play_scene" ],
      [ "Scene", "classscene_1_1_scene.html", "classscene_1_1_scene" ],
      [ "SceneManager", "classscene_1_1_scene_manager.html", "classscene_1_1_scene_manager" ],
      [ "TitleScene", "classscene_1_1_title_scene.html", "classscene_1_1_title_scene" ]
    ] ],
    [ "BONE", "struct_b_o_n_e.html", null ],
    [ "Camera", "class_camera.html", "class_camera" ],
    [ "CameraData", "struct_camera_data.html", null ],
    [ "Component", "class_component.html", "class_component" ],
    [ "ConstantBuffer0", "struct_constant_buffer0.html", null ],
    [ "ConstantBuffer1", "struct_constant_buffer1.html", null ],
    [ "ConstantBufferMaterial", "struct_constant_buffer_material.html", null ],
    [ "ConstantBufferMesh", "struct_constant_buffer_mesh.html", null ],
    [ "D3DXPARSER", "class_d3_d_x_p_a_r_s_e_r.html", null ],
    [ "Direct3D11", "class_direct3_d11.html", null ],
    [ "Direct3D9", "class_direct3_d9.html", null ],
    [ "Director", "class_director.html", "class_director" ],
    [ "File", "class_file.html", "class_file" ],
    [ "Fps", "class_fps.html", null ],
    [ "HierarchyMesh", "class_hierarchy_mesh.html", "class_hierarchy_mesh" ],
    [ "Image", "class_image.html", "class_image" ],
    [ "ImageShaderConstBuffer", "struct_image_shader_const_buffer.html", null ],
    [ "ImageVertex", "struct_image_vertex.html", null ],
    [ "Input", "class_input.html", null ],
    [ "Line", "class_line.html", "class_line" ],
    [ "MY_H_HIERARCHY", "class_m_y___h___h_i_e_r_a_r_c_h_y.html", null ],
    [ "MY_HIERARCHY", "class_m_y___h_i_e_r_a_r_c_h_y.html", null ],
    [ "MY_SKINMATERIAL", "struct_m_y___s_k_i_n_m_a_t_e_r_i_a_l.html", null ],
    [ "MY_SKINVERTEX", "struct_m_y___s_k_i_n_v_e_r_t_e_x.html", null ],
    [ "MYFRAME", "struct_m_y_f_r_a_m_e.html", null ],
    [ "MYHFRAME", "struct_m_y_h_f_r_a_m_e.html", null ],
    [ "MyHMaterial", "struct_my_h_material.html", null ],
    [ "MYHMESHCONTAINER", "struct_m_y_h_m_e_s_h_c_o_n_t_a_i_n_e_r.html", null ],
    [ "MyHVertex", "struct_my_h_vertex.html", null ],
    [ "MyHVertexNoTex", "struct_my_h_vertex_no_tex.html", null ],
    [ "MyMaterial", "struct_my_material.html", null ],
    [ "MYMESHCONTAINER", "struct_m_y_m_e_s_h_c_o_n_t_a_i_n_e_r.html", null ],
    [ "MyVertex", "struct_my_vertex.html", null ],
    [ "Object", "class_object.html", "class_object" ],
    [ "PartsMesh", "struct_parts_mesh.html", null ],
    [ "Point", "class_point.html", "class_point" ],
    [ "Primitive", "class_primitive.html", "class_primitive" ],
    [ "PrimitiveConstantBuffer", "struct_primitive_constant_buffer.html", null ],
    [ "PrimitiveConstantBuffer2D", "struct_primitive_constant_buffer2_d.html", null ],
    [ "PrimitiveVertex", "struct_primitive_vertex.html", null ],
    [ "PrimitiveVertex2D", "struct_primitive_vertex2_d.html", null ],
    [ "Quad", "class_quad.html", "class_quad" ],
    [ "SceneManager", "class_scene_manager.html", null ],
    [ "SHADER_GLOBAL_BONES", "struct_s_h_a_d_e_r___g_l_o_b_a_l___b_o_n_e_s.html", null ],
    [ "SHADER_SKIN_GLOBAL0", "struct_s_h_a_d_e_r___s_k_i_n___g_l_o_b_a_l0.html", null ],
    [ "SHADER_SKIN_GLOBAL1", "struct_s_h_a_d_e_r___s_k_i_n___g_l_o_b_a_l1.html", null ],
    [ "ShaderDirector", "class_shader_director.html", null ],
    [ "ShaderVariable", "struct_shader_variable.html", null ],
    [ "SkinMesh", "class_skin_mesh.html", "class_skin_mesh" ],
    [ "StaticMesh", "class_static_mesh.html", "class_static_mesh" ],
    [ "TellCameraData", "class_tell_camera_data.html", null ],
    [ "Transform", "class_transform.html", "class_transform" ],
    [ "Triangle", "class_triangle.html", "class_triangle" ],
    [ "Window", "class_window.html", "class_window" ]
];